name: simple_notepad_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  file_picker: ^8.0.6
  share_plus: ^10.0.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  flutter_markdown: ^0.7.4+1   # добавлена поддержка Markdown

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true